FROM python:3.12-slim-bookworm

# Install required packages for python with neovim and npm
RUN apt-get update && apt-get install -y \
    curl \
    git \
    jq \
    neovim \
    nodejs \
    npm \
    zsh 

